#This program is a mad lib
#
#River Sneed
#8/19/2016
 
print ("You gonna give me some words or Im gonna stick this in you mouth and I will kill you")
print ("give an adjective")
adj1 = input()
print ("give a verb")
verb1 = input()
print ("give me anotha one")
verb2 = input()
print ("anotha one")
verb3 = input()
print ("I want something fancy")
print ("give me a noun")
print ("a pluran noun")
pnoun1 = input()
print ("i want anotha verb")
verb4 = input()
print ("anotha one")
verb5 = input()
print ("i want one of them fancy past tense verbs")
verb6 = input()
print (" i want anotha one of those oh so fancy plural nouns")
pnoun2 = input()
print ("i want a descriptive word")
adj2 = input()
print ("i want a verb")
verb7 = input()
print (" i want anotha one of those oh so fancy plural nouns")
pnoun3 = input()
print ("now i wanna noun")
noun1 = input()
print ("i want anotha one of those good ol verbs")
verb8 = input()
print (" i want a verb")
print ("but a verb thats from the past")
verb9 = input()
print ("i want a noun ri-now")
noun2 = input()
print ("anotha one")
noun3 = input()
print ("anotha one")
print ("a funny one")
noun4 = input()
print ("i want one of them fancy past tense verbs")
verb10 = input()
print ("hand over a describer word")
adj3 = input()
print ("i want a blast from the past verb")
verb11 = input()
print ("anotha one")
verb12 = input()
print (" i wanna noun")
noun5 = input ()
print ("i want a verb in the tense of the past")
verb13 = input ()

print ("The three little piggys")
print ("by your lazy self who would only give me a couple words")
print ("Once upon a time, there were three "+ adj1 +" pigs.")
print ("One day, their mother said, you are all grown up and must "+ verb1 +" on you own.")
print ("So they left to "+ verb2 +" their houses.")
print ("The first little pig wanted only to "+ verb3 +" all day and quickly built his house out of "+ pnoun1 +".")
print ("The second little pig wanted to "+ verb4 +" and "+ verb5 +" all day so he "+ verb6 +" his house with "+ pnoun2 +".")
print ("The third "+ adj2 +" pig knew the wolf lived nearby and worked hard to "+ verb7 +" his house out of "+ pnoun3 +".")
print ("One day, the wolf knocked on the first pigs "+ noun1 +".")
print ("Let me in or Ill "+ verb8 +" your house down!")
print ("The pig did not, so the wolf "+ verb9 +" down the "+ noun2 +".")
print ("The wolf knocked on the second pigs "+ noun3 +".")
print ("let me in or Ill blow your "+ noun4 +" down!")
print ("The pig did not so the wolf "+ verb10 +" down the house.")
print ("Then the wolf knocked on the third "+ adj3 +" pigs door.")
print ("let me in or I will blow your house down!")
print (" The little pig did not so the wolf "+ verb11 +" and "+ verb12 +".")
print ("he could not blow the house down.")
print ("All the pigs went to live int the "+ noun5 +" house and they all "+ verb13 +" happily ever after")
print ("The end")
